import black_mirror from './images/black_mirror.jpg';
import chernobyl from './images/chernobyl.jpg';
import mindhunter from './images/mindhunter.jpg';
import sopranos from './images/sopranos.jpg';
import the_sinner from './images/thesinner.jpg';
import wild_wild_country from './images/wildwildcountry.jpg';

export default function getShows() {
    return [
        { id: 'black_mirror', name: 'Black Mirror', image: black_mirror, details:'Black Mirror is a British science fiction anthology television series created by Charlie Brooker, with Brooker and Annabel Jones serving as the programme showrunners. It examines modern society, particularly with regard to the unanticipated consequences of new technologies. Episodes are standalone, usually set in an alternative present or the near future, often with a dark and satirical tone, though some are more experimental and lighter.' },
        { id: 'chernobyl', name: 'Chernobyl', image: chernobyl, details:'Chernobyl dramatizes the story of the April 1986 nuclear plant disaster which occurred in the Ukrainian Soviet Socialist Republic (Soviet Union), telling the stories of the people who caused the disaster and those who responded to it.[1] The series depicts some of the lesser known stories of the disaster, including the efforts of the firefighters who were the first responders on the scene, volunteers, and teams of miners tasked with digging a critical tunnel under Reactor 4.' },
        { id: 'mind_hunter', name: 'Mind Hunter', image: mindhunter, details:'Catching a criminal often requires the authorities to get inside the villains mind to figure out how he thinks. That is the job of FBI agents Holden Ford and Bill Tench. They attempt to understand and catch serial killers by studying their damaged psyches. Along the way, the agents pioneer the development of modern serial-killer profiling. The crime drama has a strong pedigree behind the camera, with Oscar-nominated director David Fincher and Oscar-winning actress Charlize Theron among the show is executive producers.' },
        { id: 'sopranos', name: 'Sopranos', image: sopranos, details:'Tony Soprano juggles the problems of his fractious family with those of a "Family" of a different sort - the mob. He sees a therapist to deal with his professional and personal problems, which bring on panic attacks. He deals with personal and professional power struggles, affairs, violence, the threat of exposure and betrayal, and a whole bunch of people being whacked.' },
        { id: 'the_sinner', name: 'The Sinner', image: the_sinner, details:'Detective Harry Ambrose returns to his hometown in rural New York to assess an unsettling and heart-wrenching crime -- parents murdered by their 11-year-old son with no apparent motive. As Ambrose realizes there is nothing ordinary about the boy or where he came from, the investigation pulls him into the hidden darkness of his hometown. He is pitted against those who will stop at nothing to protect its secrets -- and the mysterious Vera, who proves to be a complicated, enigmatic piece to this haunting puzzle.' },
        { id: 'wild_wild_country', name: 'Wild Wild Country', image: wild_wild_country, details:'When a controversial guru builds a utopian city in the Oregon desert, it causes a massive conflict with local ranchers. This docuseries chronicles the conflict, which leads to the first bioterror attack in the United States and a massive case of illegal wiretapping. It is a pivotal, but largely forgotten, time in American cultural history that tested the country is tolerance for the separation of church and state. Brothers Mark and Jay Duplass serve as executive producers on the series.' }
    ];
}
